version: "3.8"

services:
  web:
    build: .
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    #restart: always
    ports:
      # A:B ; Map port A on the Docker host to TCP port B in the container.
      - "80:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mydb
      - TZ='Asia/Tokyo'
    env_file:
      - .env
    healthcheck:   # here
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppass"]
      interval: 20s
      timeout: 5s
      retries: 3
    volumes:
      #初期データをマウントする場所
      - ./db:/docker-entrypoint-initdb.d
      # 名前付きvolumeをdocker-composeで設定し、コンテナの/var/lib/mysqlに紐づける
      # /var/lib/mysqlがある限り init処理は実行されない
      - data:/var/lib/mysql
    #command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci'] 

volumes:
  data: # 名前付きボリュームも消してまっさらしたい